version: '3.9'

services:
  broker:
    image: broker
    build:
      context: ./broker
      dockerfile: Dockerfile
    container_name: broker
    ports:
      - "8000:8000"
      - "8001:8001"
    entrypoint: ["python3", "node_server.py", "--host", "127.0.0.1", "--port", "8000"]
    networks:
      - my_net

  node0:
    image: node
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: client-node0
    entrypoint: ["python3", "node_client.py", "--host", "127.0.0.1", "--port", "8000", "--name", "node0"]
    networks:
      - my_net

  node1:
    image: node
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: client-node1
    entrypoint: ["python3", "node_client.py", "--host", "127.0.0.1", "--port", "8000", "--name", "node1"]
    networks:
      - my_net

  node2:
    image: node
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: client-node2
    entrypoint: ["python3", "node_client.py", "--host", "127.0.0.1", "--port", "8000", "--name", "node2"]
    networks:
      - my_net

networks:
  my_net:
    driver: bridge
