version: '3.9'

services:
  server:
    build:
      context: ./broker
      dockerfile: Dockerfile
    container_name: broker-server
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      - DEFAULT_HOST=0.0.0.0
      - CLIENT_PORT=8000
      - API_PORT=8001
    networks:
      - distributed_network

  node0:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: client-node0
    environment:
      - NODE_NAME=node0
      - SERVER_HOST=broker-server
      - SERVER_PORT=8000
    networks:
      - distributed_network

  node1:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: client-node1
    environment:
      - NODE_NAME=node1
      - SERVER_HOST=broker-server
      - SERVER_PORT=8000
    networks:
      - distributed_network

  node2:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: client-node2
    environment:
      - NODE_NAME=node2
      - SERVER_HOST=broker-server
      - SERVER_PORT=8000
    networks:
      - distributed_network

networks:
  distributed_network:
    driver: bridge
